### YamlMime:ModuleUnit
uid: learn.ai-flask-python.1-set-up-environment
title: Set up a development environment
metadata:
  title: Set up a development environment
  description: Set up a development environment for building Web sites with Flask and Python
  ms.date: 06/06/2019
  author: v-jeffpr
  ms.author: christopher.harrison
  ms.topic: interactive-tutorial
  ms.prod: learning-python
  ROBOTS: NOINDEX
durationInMinutes: 15
content: |
  [!include[](includes/1-set-up-environment.md)]